name: plannotate
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - plannotate=1.2.4
  - Bio=1.8.0
  - pip
  - pip:
      - streamlit==1.8.1
      - tenacity==9.1.2
      - Bio==1.8.0
      - biopython==1.85
      - bokeh==3.7.3
